version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - local/.env
    volumes:
      - ./local/commands.yaml:/etc/chat-home-automation.yaml
    restart: always